# Generated by Django 3.1.5 on 2021-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210202_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Non-Binary')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
