# Generated by Django 3.1.5 on 2021-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='modify time')),
                ('type', models.CharField(choices=[('vm', 'Visual memory'), ('wm', 'Working memory'), ('o', 'Orientation'), ('pt', 'Perspective taking')], max_length=50, verbose_name='Type')),
                ('result', models.TextField(verbose_name='Result')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
