# Generated by Django 3.1.5 on 2021-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('vm', 'Visual memory'), ('wm', 'Working memory'), ('o', 'Orientation'), ('pt', 'Perspective taking'), ('g', 'Game')], max_length=10, verbose_name='Type'),
        ),
    ]
